# basic options, i can say whatever here
title: Carmel-first-portfolio
author: Smart Guy
email: your-email@domain.com
description: A wonderful site
twitter_username: carmel7218
github_username: carmelgourdet

# Build settings
markdown: kramdown
theme: minima



